// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD1ZTLEG80lMykfKeh_5MmSGG-Rx0y0Fo',
    appId: '1:368160375980:web:b76de5558e6b3899d88b09',
    messagingSenderId: '368160375980',
    projectId: 'app-ban-hang-mini',
    authDomain: 'app-ban-hang-mini.firebaseapp.com',
    storageBucket: 'app-ban-hang-mini.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPMoNkHVxyxEXxBDOEL8hS_-brZAKrSlE',
    appId: '1:368160375980:android:5b331c226a088ad8d88b09',
    messagingSenderId: '368160375980',
    projectId: 'app-ban-hang-mini',
    storageBucket: 'app-ban-hang-mini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZcGacR6CxRo9UhlfXTb116Rz-4Q0AGY',
    appId: '1:368160375980:ios:af1680eec7399586d88b09',
    messagingSenderId: '368160375980',
    projectId: 'app-ban-hang-mini',
    storageBucket: 'app-ban-hang-mini.firebasestorage.app',
    iosBundleId: 'com.example.salesManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeZcGacR6CxRo9UhlfXTb116Rz-4Q0AGY',
    appId: '1:368160375980:ios:af1680eec7399586d88b09',
    messagingSenderId: '368160375980',
    projectId: 'app-ban-hang-mini',
    storageBucket: 'app-ban-hang-mini.firebasestorage.app',
    iosBundleId: 'com.example.salesManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD1ZTLEG80lMykfKeh_5MmSGG-Rx0y0Fo',
    appId: '1:368160375980:web:7048c9508beaaef6d88b09',
    messagingSenderId: '368160375980',
    projectId: 'app-ban-hang-mini',
    authDomain: 'app-ban-hang-mini.firebaseapp.com',
    storageBucket: 'app-ban-hang-mini.firebasestorage.app',
  );
}
